# Generated by Django 3.0 on 2019-12-16 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('coins', models.IntegerField()),
                ('level', models.IntegerField()),
                ('type', models.CharField(max_length=2)),
                ('about_text', models.TextField()),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('isPremium', models.BooleanField()),
                ('playLimit', models.IntegerField()),
                ('last_visit_date', models.DateTimeField()),
                ('warn_value', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField()),
                ('profile_pic', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('play_count', models.BigIntegerField()),
                ('thumbnail', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('thumbnail', models.CharField(max_length=1500)),
                ('about_text', models.TextField()),
                ('how_to_play_text', models.TextField()),
                ('link', models.CharField(blank=True, max_length=1500, null=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('play_count', models.BigIntegerField()),
                ('category1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cat_1', to='cupApp.Category')),
                ('category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cat_2', to='cupApp.Category')),
                ('category3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cat_3', to='cupApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('detail', models.TextField()),
                ('submit_time', models.DateTimeField(default=datetime.datetime(2019, 12, 16, 11, 38, 15, 55461, tzinfo=utc))),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2019, 12, 16, 11, 38, 15, 55461, tzinfo=utc))),
                ('is_checked', models.BooleanField()),
                ('is_starred', models.BooleanField()),
                ('suggestion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='suggestion_owner', to='cupApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.IntegerField()),
                ('average_score', models.BigIntegerField()),
                ('last_score', models.BigIntegerField()),
                ('rank', models.IntegerField()),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_game', to='cupApp.Game')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_owner', to='cupApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BigIntegerField()),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_game', to='cupApp.Game')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_owner', to='cupApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('text', models.TextField()),
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_game', to='cupApp.Game')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='cupApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=50)),
                ('is_owned', models.BooleanField()),
                ('thumbnail', models.CharField(max_length=1500)),
                ('game_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_game', to='cupApp.Game')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_owner', to='cupApp.Account')),
            ],
        ),
    ]
