# Generated by Django 3.0 on 2019-12-18 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cupApp', '0006_auto_20191218_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 55, 3, 904452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 55, 3, 904452, tzinfo=utc)),
        ),
    ]
