# Generated by Django 3.0 on 2019-12-19 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cupApp', '0007_auto_20191218_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 19, 6, 26, 21, 752088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 6, 26, 21, 756213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 6, 26, 21, 756213, tzinfo=utc)),
        ),
    ]
