# Generated by Django 3.0 on 2019-12-19 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cupApp', '0009_auto_20191219_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score_date',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 6, 37, 17, 848526, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 6, 37, 17, 848526, tzinfo=utc)),
        ),
    ]
