# Generated by Django 3.0 on 2019-12-25 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cupApp', '0020_auto_20191225_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_visit_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 15, 41, 31, 973811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 15, 41, 31, 973811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 15, 41, 31, 973811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 15, 41, 31, 973811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 15, 41, 31, 983908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 15, 41, 31, 983908, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('favouriteId', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_game', to='cupApp.Game')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_owner', to='cupApp.Account')),
            ],
        ),
    ]
