# Generated by Django 3.0 on 2019-12-26 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cupApp', '0024_auto_20191226_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='game_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_visit_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 17, 30, 13, 717694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 17, 30, 13, 717694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 17, 30, 13, 718694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 17, 30, 13, 719704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 17, 30, 13, 721705, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 17, 30, 13, 721705, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
