# Generated by Django 3.0.1 on 2020-01-02 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cupApp', '0028_auto_20191229_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='is_owned',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='last_visit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 18, 29, 9, 932146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 18, 29, 9, 932146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 18, 29, 9, 932146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 18, 29, 9, 932146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 18, 29, 9, 932146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 18, 29, 9, 932146, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ownedBadges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_badge_name', to='cupApp.Badge')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_owner', to='cupApp.Account')),
            ],
        ),
    ]
