# Generated by Django 3.0.2 on 2020-01-11 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cupApp', '0037_auto_20200109_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_visit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 9, 50, 53, 608294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='playLimit',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='account',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 9, 50, 53, 608294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 9, 50, 53, 609285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 9, 50, 53, 610294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 9, 50, 53, 613295, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 9, 50, 53, 612295, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ScoreSubmission',
            fields=[
                ('score', models.IntegerField()),
                ('score_date', models.DateTimeField(default=datetime.datetime(2020, 1, 11, 9, 50, 53, 614295, tzinfo=utc))),
                ('submissionId', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_submission_game', to='cupApp.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_owner', to='cupApp.Account')),
            ],
        ),
    ]
