# Generated by Django 3.0 on 2020-01-12 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cupApp', '0040_auto_20200111_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ban_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_visit_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 10, 26, 2, 778492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 10, 26, 2, 778492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 10, 26, 2, 778492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 10, 26, 2, 778492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scoresubmission',
            name='score_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 10, 26, 2, 788492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 10, 26, 2, 788492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 10, 26, 2, 788492, tzinfo=utc)),
        ),
    ]
