# Generated by Django 3.0 on 2019-12-16 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cupApp', '0002_auto_20191216_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='coins',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='playLimit',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(default='FU', max_length=2),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 13, 40, 55, 490631, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 13, 40, 55, 490631, tzinfo=utc)),
        ),
    ]
